# GitHub Sponsors and other funding platforms for VideoOverlayKit.
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [alichherawalla]
custom:
  - 'https://wednesday.is'
  - 'https://github.com/alichherawalla/video-overlay-kit'
